[colours]
sector_vertical_limits = [100, 41, 41, 41]
ac_not_concerned = [142, 142, 142]
ac_notified = [84, 179, 108]
ac_assumed = [209, 209, 209]
ac_transferred = [169, 202, 119]
ac_redundant = [114, 216, 250]
conflict_group_moon = [75, 221, 75]
conflict_group_losange = [255, 174, 23]
conflict_group_star = [255, 255, 127]

[ac_symbols]
size = 5
number_of_trails=8

[menu]
menu_position = 329

[[sector_vertical_limit]]
text = "295\r\n000"
position = ["N048.54.35.916", "E000.31.07.566"]
size = 40
controller_me = "FF"
controller_others = ["RR","RRU"]

[[sector_vertical_limit]]
text = "295\r\n000"
position = ["N050.00.28.922", "E002.46.35.408"]
size = 40
controller_me = "FF"
controller_others = ["EE","EEU"]

[[sector_vertical_limit]]
text = "195\r\n000"
position = ["N047.52.23.054", "E001.57.42.380"]
size = 30
controller_me = "FF"
controller_others=["BB","BBU"]

[[sector_vertical_limit]]
text = "660\r\n195"
position = ["N047.25.35.052", "E004.48.26.087"]
size = 30
controller_me = "FF"
controller_others=["EE"]